# --- 1. C?u hình Server ---
server.port=8080

# --- 2. C?u hình Database (MySQL Docker) ---
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- 3. C?u hình JPA / Hibernate ---
# T? ??ng c?p nh?t b?ng khi s?a code Entity (update/create/none)
spring.jpa.hibernate.ddl-auto=update
# Hi?n câu SQL trong console ?? debug
spring.jpa.show-sql=true
# Format SQL cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
# Dialect chu?n cho MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- 4. C?u hình Upload File ---
# Kích th??c t?i ?a 1 file
spring.servlet.multipart.max-file-size=10MB
# T?ng kích th??c request
spring.servlet.multipart.max-request-size=10MB
# Th? m?c l?u ?nh
file.upload-dir=uploads

# --- 5. C?u hình Logging (C? b?n) ---
# Ch? hi?n log INFO tr? lên (b? qua Debug rác c?a Spring)
logging.level.root=INFO
# Riêng gói d? án c?a mình thì hi?n DEBUG ?? soi l?i
logging.level.com.project.inventory=DEBUG

# --- C?u hình JWT (JSON Web Token) ---
# Ch? ký bí m?t (Secret Key) - Ph?i là chu?i mã hóa c?c dài. Hacker có tr?m ???c Token mà không có cái Key này thì c?ng không làm gi? ???c.
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Th?i h?n c?a vé (Tính b?ng mili-giây). VD: 86400000 = 24 gi?
application.security.jwt.expiration=86400000