# --- 1. Cau hinh Server ---
server.port=8080

# --- 2. Cau hinh Database (MySQL Docker) ---
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- 3. Cau hinh JPA / Hibernate ---
# Tu dong cap nhat bang khi sua code Entity (update/create/none)
spring.jpa.hibernate.ddl-auto=update
# Hien cau SQL trong console de debug
spring.jpa.show-sql=true
# Format SQL cho de doc
spring.jpa.properties.hibernate.format_sql=true
# Dialect chuan cho MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- 4. Cau hinh Upload File ---
# Kich thuoc toi da 1 file
spring.servlet.multipart.max-file-size=10MB
# Tong kich thuoc request
spring.servlet.multipart.max-request-size=10MB
# Thu muc luu anh
file.upload-dir=uploads

# --- 5. Cau hinh Logging (Co ban) ---
# Chi hien log INFO tro len (bo qua Debug rac cua Spring)
logging.level.root=INFO
# Rieng goi du an cua minh thi hien DEBUG de soi loi
logging.level.com.project.inventory=DEBUG

# --- Cau hinh JWT (JSON Web Token) ---
# Chu ky bi mat (Secret Key) - Phai la chuoi ma hoa cuc dai. Hacker co trom duoc Token ma khong co cai Key nay thi cung khong lam gia duoc.
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thoi han cua ve (Tinh bang mili-giay). VD: 86400000 = 24 gio
application.security.jwt.expiration=86400000