name: Spring Boot CI Pipeline

# 1. Kích hoạt Bot khi có ai push code lên nhánh main/develop hoặc tạo Pull Request
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest # Chạy trên server Linux xịn nhất của GitHub

    steps:
      # Bước 1: Kéo source code từ GitHub về con server ảo này
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt môi trường Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Bước 3: Chạy toàn bộ Unit Test bằng Maven (Bỏ ./ đi)
      - name: Run Maven Build and Tests
        run: mvn clean verify